import pandas as pd
import re

def clean_text(text):
    """
    Basic text cleaning function for student reflections.
    """
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def preprocess_data(input_path, output_path):
    """
    Load raw data, clean text, and save to output.
    Expected CSV columns: 'text', 'anxiety_level'
    """
    try:
        df = pd.read_csv(input_path)
        df['text'] = df['text'].apply(clean_text)
        
        # Mapping labels to integers
        label_map = {"Low": 0, "Moderate": 1, "High": 2}
        if 'anxiety_level' in df.columns:
            df['label'] = df['anxiety_level'].map(label_map)
        
        df.to_csv(output_path, index=False)
        print(f"Preprocessed data saved to {output_path}")
    except Exception as e:
        print(f"Error preprocessing data: {e}")

if __name__ == "__main__":
    # Path to the data generated by generate_synthetic_data.py
    input_csv = "data/raw/mental_health_dataset_with_text.csv"
    output_csv = "data/processed/processed_data.csv"
    
    preprocess_data(input_csv, output_csv)
